//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminWpfApp.RunReportProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="TopographyAdminSvc", ConfigurationName="RunReportProxy.IRunReport")]
    public interface IRunReport {
        
        [System.ServiceModel.OperationContractAttribute(Action="TopographyAdminSvc/IRunReport/RunAllUsersReport", ReplyAction="TopographyAdminSvc/IRunReport/RunAllUsersReportResponse")]
        string RunAllUsersReport(string timeframe);
        
        [System.ServiceModel.OperationContractAttribute(Action="TopographyAdminSvc/IRunReport/RunAllUsersReport", ReplyAction="TopographyAdminSvc/IRunReport/RunAllUsersReportResponse")]
        System.Threading.Tasks.Task<string> RunAllUsersReportAsync(string timeframe);
        
        [System.ServiceModel.OperationContractAttribute(Action="TopographyAdminSvc/IRunReport/RunAllTopicsReport", ReplyAction="TopographyAdminSvc/IRunReport/RunAllTopicsReportResponse")]
        string RunAllTopicsReport(string timeframe);
        
        [System.ServiceModel.OperationContractAttribute(Action="TopographyAdminSvc/IRunReport/RunAllTopicsReport", ReplyAction="TopographyAdminSvc/IRunReport/RunAllTopicsReportResponse")]
        System.Threading.Tasks.Task<string> RunAllTopicsReportAsync(string timeframe);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRunReportChannel : AdminWpfApp.RunReportProxy.IRunReport, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RunReportClient : System.ServiceModel.ClientBase<AdminWpfApp.RunReportProxy.IRunReport>, AdminWpfApp.RunReportProxy.IRunReport {
        
        public RunReportClient() {
        }
        
        public RunReportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RunReportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RunReportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RunReportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RunAllUsersReport(string timeframe) {
            return base.Channel.RunAllUsersReport(timeframe);
        }
        
        public System.Threading.Tasks.Task<string> RunAllUsersReportAsync(string timeframe) {
            return base.Channel.RunAllUsersReportAsync(timeframe);
        }
        
        public string RunAllTopicsReport(string timeframe) {
            return base.Channel.RunAllTopicsReport(timeframe);
        }
        
        public System.Threading.Tasks.Task<string> RunAllTopicsReportAsync(string timeframe) {
            return base.Channel.RunAllTopicsReportAsync(timeframe);
        }
    }
}
